-- Denizen SQLite schema — migration 0001, the original schema.sql exactly
-- as it stood before this app had any production data. From here on,
-- schema changes are new numbered files in this directory (0002, 0003,
-- ...), never edits to this one — see internal/db/db.go's migration
-- runner. A fresh database runs every migration in order, starting here;
-- an existing database (with a `users` table already present, from before
-- this migration system existed) has this one recorded as already-applied
-- without being re-run, since CREATE TABLE would fail against tables that
-- are already there.
--
-- Conventions:
--   * All IDs are UUIDs (TEXT), generated by the application — consistent
--     with the API, which addresses every resource by a stable ID, not a
--     name/path (see docs/ARCHITECTURE.md).
--   * Timestamps are Unix epoch seconds (INTEGER), not TEXT — cheap to
--     compare, no timezone parsing.
--   * Booleans are INTEGER 0/1 (SQLite has no native boolean type).

PRAGMA foreign_keys = ON;

-- One row per account. Created only via an invite (see `invites`) — there is
-- no public self-registration.
CREATE TABLE users (
    id                 TEXT PRIMARY KEY,
    username           TEXT NOT NULL UNIQUE,
    password_hash      TEXT NOT NULL,
    is_admin           INTEGER NOT NULL DEFAULT 0,
    quota_bytes        INTEGER NOT NULL,
    storage_used_bytes INTEGER NOT NULL DEFAULT 0, -- incremental counter; trash counts toward this
    disabled           INTEGER NOT NULL DEFAULT 0,
    created_at         INTEGER NOT NULL
);

-- One-time invite codes. A user account only comes into existence by
-- redeeming one of these (admin-only creation).
CREATE TABLE invites (
    id           TEXT PRIMARY KEY,
    code         TEXT NOT NULL UNIQUE,
    created_by   TEXT REFERENCES users(id), -- NULL for the bootstrap invite (no admin exists yet)
    grants_admin INTEGER NOT NULL DEFAULT 0, -- 1 only for the bootstrap invite
    quota_bytes  INTEGER,           -- NULL = use the server's global default quota
    expires_at   INTEGER NOT NULL,
    used_at      INTEGER,           -- NULL = not redeemed yet
    used_by      TEXT REFERENCES users(id),
    created_at   INTEGER NOT NULL
);

-- Issued refresh tokens, so a logout/compromise can revoke a specific one
-- instead of invalidating every session. Only the hash is stored, never the
-- raw token.
CREATE TABLE refresh_tokens (
    id         TEXT PRIMARY KEY,
    user_id    TEXT NOT NULL REFERENCES users(id),
    token_hash TEXT NOT NULL,
    expires_at INTEGER NOT NULL,
    revoked_at INTEGER,            -- NULL = still valid
    created_at INTEGER NOT NULL
);

CREATE INDEX idx_refresh_tokens_user ON refresh_tokens(user_id);

-- Files and folders. A row with type = 'folder' groups other rows under it
-- via parent_id; a row with type = 'file' has actual content on disk at the
-- path the application derives from walking parent_id up to the root (see
-- docs/ARCHITECTURE.md's storage layout — the on-disk path mirrors this tree
-- but the tree itself, not the path, is the source of truth).
CREATE TABLE items (
    id           TEXT PRIMARY KEY,
    owner_id     TEXT NOT NULL REFERENCES users(id),
    parent_id    TEXT REFERENCES items(id),  -- NULL = the user's root folder
    name         TEXT NOT NULL,
    type         TEXT NOT NULL CHECK (type IN ('file', 'folder')),
    size_bytes   INTEGER NOT NULL DEFAULT 0, -- 0 for folders
    mime_type    TEXT,                       -- NULL for folders
    checksum     TEXT,                       -- sha256 of file content; NULL for folders
    deleted_at   INTEGER,                    -- NULL = active, non-NULL = in trash since this time
    created_at   INTEGER NOT NULL,
    updated_at   INTEGER NOT NULL
);

CREATE INDEX idx_items_owner    ON items(owner_id);
CREATE INDEX idx_items_parent   ON items(parent_id);
CREATE INDEX idx_items_deleted  ON items(deleted_at);

-- No two active items with the same name in the same folder. This is a
-- safety net — the application is expected to auto-suffix on collision
-- ("file (1).pdf") before it ever gets here.
CREATE UNIQUE INDEX idx_items_unique_name_per_folder
    ON items(owner_id, IFNULL(parent_id, ''), name)
    WHERE deleted_at IS NULL;

-- Public share links. A link's mere existence is the grant — anyone holding
-- the raw token (and satisfying requires_auth, if set) can access the item
-- it points to. Only the token's hash is stored (same reasoning as
-- refresh_tokens: a database leak alone shouldn't hand out live share
-- links), which is why revocation and listing are keyed by the row's own
-- id, not by the token — the raw value is only ever shown once, at
-- creation, and deliberately not retrievable after that (see
-- docs/ARCHITECTURE.md). Revoking a share is a row delete, not a soft
-- delete.
CREATE TABLE shares (
    id            TEXT PRIMARY KEY,
    item_id       TEXT NOT NULL REFERENCES items(id),
    token_hash    TEXT NOT NULL UNIQUE,
    created_by    TEXT NOT NULL REFERENCES users(id),
    requires_auth INTEGER NOT NULL DEFAULT 0, -- 1 = visitor must be logged in to some account
    expires_at    INTEGER,                    -- NULL = never expires
    created_at    INTEGER NOT NULL
);

CREATE INDEX idx_shares_item ON shares(item_id);
